Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('pinctrl', src, depend = ['LOMBO_GPIO', 'ARCH_LOMBO_N7'], CPPPATH = CPPPATH)

Return('group')
