Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd,
	   os.path.join(cwd, "../../h264_decode_component")]
LIBPATH = os.path.join(cwd, "../../h264_decode_component/libs")
group = DefineGroup('omx_core', src, depend = [""], CPPPATH = CPPPATH)

Return('group')
