Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('gpadc', src, depend = ['ARCH_LOMBO_N7', 'LOMBO_GPADC'], CPPPATH = CPPPATH)

Return('group')