import os
import shutil
Import('RTT_ROOT')
#Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd,
            RTT_ROOT +'/../include',
            cwd+'/includes',
            cwd+'/includes/media_display',
            cwd+'/includes/jpeg_component']

folder = os.path.exists('jpeg_component/libs')
if not folder:
    os.mkdir('jpeg_component/libs')

#print cwd
#print src[1], len(src)
#print CPPPATH
#raise Exception, "loop print"

group = DefineGroup('media_mod',
                    src, depend = [""],
                    CPPPATH = CPPPATH)

# build for sub-directory
list = os.listdir(cwd)
objs = []
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
group = group + objs

#if os.path.exists("../../includes/mod") == False:
#    os.mkdir("../../includes/mod")
#shutil.copy("./mod_media.h", "../../includes")
shutil.copy(RTT_ROOT + '/../case/cdr/mod/mod_media/mod_media.h', RTT_ROOT + '/../case/cdr/includes')

Return('group')
