Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd,
	   os.path.join(cwd, "../inc_ex"),
	   os.path.join(cwd, "../omxbase/inc"),
	   os.path.join(cwd, "../omxbase")]
group = DefineGroup('splitter_component', src, depend = [""], CPPPATH = CPPPATH)

Return('group')
