Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('omx_test', src, depend = ['LOMBO_TEST_MEDIA'], CPPPATH = CPPPATH)

Return('group')
