Import('RTT_ROOT')
Import('rtconfig')
from building import *
#Import('env')

#env.Append(CPPPATH=paths)
cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = []

if GetDepend('RT_USING_LBMEDIA'):
	group = DefineGroup('media', src, depend = ['RT_USING_LBMEDIA'], CPPPATH = CPPPATH)

	# build for sub-directory
	list = os.listdir(cwd)
	for d in list:
		path = os.path.join(cwd, d)
		if os.path.isfile(os.path.join(path, 'SConscript')):
			group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
