Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('common', src, depend = [''], CPPPATH = CPPPATH)

#
# add subdirs' SConscript
#
objs = []
list = []
if GetDepend('RT_USING_MODULE'):
    list = ['plugin_manage']

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
group = group + objs

Return('group')
