Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd,
	   os.path.join(cwd, "../inc_ex"),
	   os.path.join(cwd, "../omxbase/inc"),
	   os.path.join(cwd, "../omxbase")]

# add static lib
LIBPATH = os.path.join(cwd, "libs")
LIBS = ['libaacdec.a','libwavdec.a']
group = DefineGroup('adec_component', src, depend = [""], CPPPATH = CPPPATH, LIBS = LIBS, LIBPATH = LIBPATH)
#group = DefineGroup('adec_component', src, depend = [""], CPPPATH = CPPPATH)

Return('group')
