Import('RTT_ROOT')
Import('rtconfig')
from building import *
#Import('env')

#env.Append(CPPPATH=paths)
cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]
CPPPATH += [ cwd + '../../../../eos/bsp/lombo/libraries/demo/inc/']
CPPPATH += [ cwd + '../muxer_component/include/']

# add static lib
src += ['libs/libfdk-aac-0.1.6.a', 'libs/libwavenc.a']
#src += Glob('/libs/*.a')

group = DefineGroup('media', src, depend = ['ARCH_LOMBO_N7'], CPPPATH = CPPPATH)

# build for sub-directory
list = os.listdir(cwd)
objs = []

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

if GetDepend('ARCH_LOMBO_N7'):
	group = group + objs


Return('group')
