Import('RTT_ROOT')
Import('rtconfig')
from building import *

#cwd = os.path.join(str(Dir('#')), 'drivers')
cwd = GetCurrentDir()

#
# add the general drivers.
#
src = Split("""
board.c
cache.c
""")

if GetDepend('DEBUG_LIST'):
	src += ['list_debug.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

#
# add subdirs' SConscript
#
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = group + objs

Return('group')
