Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
vic_det_dev.c
vic_det_drv.c
""")

CPPPATH = [cwd, os.path.join(str(Dir('#')))]
CPPPATH += [os.path.join(str(Dir('#')), 'drivers')]

group = DefineGroup('vic_det', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
objs = []
for d in list :
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = group + objs

Return('group')

