Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('pwm', src, depend = ['ARCH_LOMBO_N7', 'RT_USING_PWM'], CPPPATH = CPPPATH)

Return('group')
