Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')

cwd = GetCurrentDir()
CPPPATH = [cwd]

objs = []
list = os.listdir(cwd)

group = DefineGroup('vc', src, depend = [], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs = objs + group

Return('objs')
