Import('RTT_ROOT')
#Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd,
            RTT_ROOT +'/../include']

group = DefineGroup('media_display',
                    src,
                    depend = [""],
                    CPPPATH = CPPPATH)

# build for sub-directory
list = os.listdir(cwd)
objs = []
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
group = group + objs

Return('group')
