Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd, RTT_ROOT + "/bsp/lombo/include", str(Dir('#'))]

group = DefineGroup('plg_manage', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
