/*
 * clk_csp.c - initial clk_hw_t for diferent csp.
 *
 * Copyright (C) 2016-2018, LomboTech Co.Ltd.
 * Author: lomboswer <lomboswer@lombotech.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
#define DBG_SECTION_NAME	"CLK_CSP"

#include <clk_debug.h>
#include "csp.h"
#include "clk.h"
#include "clk_csp.h"
#include "clk_private.h"

clk_hw_t clk_hw_all[CLK_NUM];

void init_clk_hw(void)
{
	memset(clk_hw_all, 0, sizeof(clk_hw_all));
	INIT_FIXED_CLK(OSC32K, CLK_32K);
	INIT_FIXED_CLK(OSC24M, CLK_24M);
	INIT_FIXED_CLK(NULL_CLK, 0);

	INIT_PLL_CLK(CPU_PLL, VA_PRCM_CPU_PLL_EN);
	INIT_PLL_CLK(SDRAM_PLL, VA_PRCM_SDRAM_PLL_EN);
	INIT_PLL_CLK(PERH0_PLL_VCO, VA_PRCM_PERH0_PLL_EN);
	INIT_PLL_CLK(AUDIO_PLL_DIV0, VA_PRCM_AUDIO_PLL_EN);
	INIT_PLL_CLK(VC_PLL, VA_PRCM_VC_PLL_EN);
	INIT_PLL_CLK(PERH1_PLL, VA_PRCM_PERH1_PLL_EN);

#ifdef ARCH_LOMBO_N7V0
	INIT_PLL_CLK(VIDEO_PLL, VA_PRCM_VIDEO_PLL_EN);
#endif

#ifdef ARCH_LOMBO_N7V1
	INIT_PLL_CLK(DISP_PLL, VA_PRCM_DISP_PLL_EN);
	WRITEREG32(VA_PRCM_DISP_PLL_TUNE0, 0x0060D1D8);	/* set tune0 register */
	INIT_PLL_CLK(AX_PLL, VA_PRCM_AX_PLL_EN);
	INIT_PLL_CLK(PERH2_PLL, VA_PRCM_PERH2_PLL_EN);
#endif

#ifdef ARCH_LOMBO_N7V0
	INIT_DEVIDER_CLK(CPU_AXI_CLK, VA_PRCM_CPU_AXI_CLK_CTRL, 16, 2, CLK_ID_CPU_CLK);
#endif

	INIT_DEVIDER_CLK(PERH0_PLL_DIVM, VA_PRCM_PERH0_PLL_FAC, 4, 2,
		CLK_ID_PERH0_PLL_VCO);
	INIT_DEVIDER_CLK(AUDIO_PLL_DIVM, VA_PRCM_AUDIO_PLL_FAC, 4, 2,
		CLK_ID_AUDIO_PLL_DIV0);

	INIT_FIXED_FACT_CLK(APB_CLK, 1, 2, CLK_ID_AHB_CLK);
	INIT_FIXED_FACT_CLK(PERH0_PLL_DIV2, 1, 2, CLK_ID_PERH0_PLL_VCO);
	INIT_FIXED_FACT_CLK(PERH0_PLL_DIV4, 1, 4, CLK_ID_PERH0_PLL_VCO);
	INIT_FIXED_FACT_CLK(PERH0_PLL_DIV8, 1, 8, CLK_ID_PERH0_PLL_VCO);
	INIT_FIXED_FACT_CLK(AUDIO_PLL_DIV7, 1, 7, CLK_ID_AUDIO_PLL_DIV0);
	INIT_FIXED_FACT_CLK(AUDIO_PLL_DIV17, 1, 17, CLK_ID_AUDIO_PLL_DIV0);

	INIT_M_CLK(CPU_CLK, VA_PRCM_CPU_AXI_CLK_CTRL, MODULE_INVALID_ENABLE_SHIFT,
		CLK_DIVIDER_POWER_OF_TWO, 4, 2, 0, 0,
		CLK_ID_OSC24M, CLK_ID_OSC32K, CLK_ID_CPU_PLL, 0);
	INIT_M_CLK(AHB_CLK, VA_PRCM_AHB_APB_CLK_CTRL, MODULE_INVALID_ENABLE_SHIFT,
		0, 4, 2, 0, 0,
		CLK_ID_OSC24M, CLK_ID_OSC32K, CLK_ID_PERH0_PLL_DIV2, 0);
	INIT_M_CLK(MEM_AXI_CLK, VA_PRCM_MAXI_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 2, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_OSC32K,
		CLK_ID_PERH0_PLL_VCO);
	INIT_M_CLK(SDRAM_CLK, VA_PRCM_SDRAM_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		CLK_DIVIDER_POWER_OF_TWO, 4, 2, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_SDRAM_PLL, 0, 0);
	INIT_M_CLK(SDRAM_BANDW_CLK, VA_PRCM_SDRAM_BM_CLK_CTRL,
		MODULE_DEFAULT_ENABLE_SHIFT,
		0, 0, 0, 0, 0,
		CLK_ID_OSC24M, 0, 0, 0);
	INIT_M_CLK(SDC0_CLK, VA_PRCM_SDC0_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		CLK_DIVIDER_NORMAL_TWO, 4, 4, 8, 4,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_VCO,
		CLK_ID_PERH1_PLL);
	INIT_M_CLK(SDC1_CLK, VA_PRCM_SDC1_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		CLK_DIVIDER_NORMAL_TWO, 4, 4, 8, 4,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_VCO,
		CLK_ID_PERH1_PLL);

#ifdef ARCH_LOMBO_N7V1
	INIT_M_CLK(SDC2_CLK, VA_PRCM_SDC2_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		CLK_DIVIDER_NORMAL_TWO, 4, 4, 8, 4,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_VCO,
		CLK_ID_PERH1_PLL);
#endif

	INIT_M_CLK(SPI0_CLK, VA_PRCM_SPI0_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		CLK_DIVIDER_NORMAL_TWO, 4, 3, 8, 4,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV2,
		CLK_ID_PERH1_PLL);
	INIT_M_CLK(SPI1_CLK, VA_PRCM_SPI1_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		CLK_DIVIDER_NORMAL_TWO, 4, 3, 8, 4,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV2,
		CLK_ID_PERH1_PLL);
	INIT_M_CLK(SPI2_CLK, VA_PRCM_SPI2_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		CLK_DIVIDER_NORMAL_TWO, 4, 3, 8, 4,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV2,
		CLK_ID_PERH1_PLL);

/* VC */
#ifdef ARCH_LOMBO_N7V0
	INIT_M_CLK(VC_CLK, VA_PRCM_VC_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 4, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_VC_PLL, 0, 0);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_M_CLK(VC_ENC_CLK, VA_PRCM_VC_ENC_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 4, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_VC_PLL, 0, 0);
	INIT_M_CLK(VC_DEC_CLK, VA_PRCM_VC_DEC_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 4, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_VC_PLL, 0, 0);
#endif

	INIT_M_CLK(DPU_SCLK0, VA_PRCM_DPU_SCLK0_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 4, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_PERH0_PLL_DIV2, CLK_ID_VC_PLL, 0);

/* DPU_SCLK1, clock source different */
#ifdef ARCH_LOMBO_N7V0
	INIT_M_CLK(DPU_SCLK1, VA_PRCM_DPU_SCLK1_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 4, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_VIDEO_PLL, CLK_ID_VC_PLL, 0);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_M_CLK(DPU_SCLK1, VA_PRCM_DPU_SCLK1_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 4, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_DISP_PLL, CLK_ID_VC_PLL, 0);
#endif

/* AX_CLK */
#ifdef ARCH_LOMBO_N7V0
	INIT_M_CLK(AX_CLK, VA_PRCM_AX_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_PERH0_PLL_VCO, CLK_ID_SDRAM_PLL, 0);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_M_CLK(AX_CLK, VA_PRCM_AX_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_AX_PLL, 0, 0);
#endif

/* I2S */
#ifdef ARCH_LOMBO_N7V0
	INIT_M_CLK(I2S_CLK, VA_PRCM_I2S_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_AUDIO_PLL_DIVM,
		CLK_ID_AUDIO_PLL_DIV7, CLK_ID_AUDIO_PLL_DIV17);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_M_CLK(I2S0_CLK, VA_PRCM_I2S0_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_AUDIO_PLL_DIVM,
		CLK_ID_AUDIO_PLL_DIV7, CLK_ID_AUDIO_PLL_DIV17);
	INIT_M_CLK(I2S1_CLK, VA_PRCM_I2S1_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_AUDIO_PLL_DIVM,
		CLK_ID_AUDIO_PLL_DIV7, CLK_ID_AUDIO_PLL_DIV17);
#endif

	init_clk_i2s();

	INIT_M_CLK(I2C0_CLK, VA_PRCM_I2C0_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);
	INIT_M_CLK(I2C1_CLK, VA_PRCM_I2C1_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);
	INIT_M_CLK(I2C2_CLK, VA_PRCM_I2C2_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);
	INIT_M_CLK(I2C3_CLK, VA_PRCM_I2C3_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);

	/* uart0, add clock source at n7v1 */
#ifdef ARCH_LOMBO_N7V0
	INIT_M_CLK(UART0_CLK, VA_PRCM_UART0_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_M_CLK(UART0_CLK, VA_PRCM_UART0_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, CLK_ID_OSC32K);
#endif

	INIT_M_CLK(UART1_CLK, VA_PRCM_UART1_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);
	INIT_M_CLK(UART2_CLK, VA_PRCM_UART2_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);
	INIT_M_CLK(UART3_CLK, VA_PRCM_UART3_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV8, 0);
	INIT_M_CLK(MBIST_CLK, VA_PRCM_MBIST_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 4, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_PERH0_PLL_DIV2, 0);

#ifdef ARCH_LOMBO_N7V1
	INIT_M_CLK(GPADC_CLK, VA_PRCM_GPADC_CLK_CTRL, MODULE_DEFAULT_ENABLE_SHIFT,
		0, 4, 1, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_OSC24M, CLK_ID_OSC32K, 0);
	INIT_M_CLK(GMAC_CLK, VA_PRCM_GMAC_CLK_CTRL, 7,
		0, 4, 3, 0, 0,
		CLK_ID_NULL_CLK, CLK_ID_PERH2_PLL, 0, 0);
#endif

	/* AHB BUS Clock Gating Register 0 */
	INIT_GATE_CLK(AHB_DMA_GATE, VA_PRCM_AHB_GAT0, 0, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_PTIMER_GATE, VA_PRCM_AHB_GAT0, 1, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_AES_GATE, VA_PRCM_AHB_GAT0, 6, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SDRAM_GATE, VA_PRCM_AHB_GAT0, 16, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SDC0_GATE, VA_PRCM_AHB_GAT0, 17, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SDC1_GATE, VA_PRCM_AHB_GAT0, 18, CLK_ID_AHB_CLK);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(AHB_SDC2_GATE, VA_PRCM_AHB_GAT0, 19, CLK_ID_AHB_CLK);
#endif

	INIT_GATE_CLK(AHB_SPI0_GATE, VA_PRCM_AHB_GAT0, 21, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SPI1_GATE, VA_PRCM_AHB_GAT0, 22, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SPI2_GATE, VA_PRCM_AHB_GAT0, 23, CLK_ID_AHB_CLK);

	/* AHB BUS Clock Gating Register 1 */
	INIT_GATE_CLK(AHB_VISS_GATE, VA_PRCM_AHB_GAT1, 0, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_DPU_GATE, VA_PRCM_AHB_GAT1, 2, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_DOSS_GATE, VA_PRCM_AHB_GAT1, 4, CLK_ID_AHB_CLK);

	/* VC */
#ifdef ARCH_LOMBO_N7V0
	INIT_GATE_CLK(AHB_VC_GATE, VA_PRCM_AHB_GAT1, 12, CLK_ID_AHB_CLK);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(AHB_VC_DEC_GATE, VA_PRCM_AHB_GAT1, 11, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_VC_ENC_GATE, VA_PRCM_AHB_GAT1, 12, CLK_ID_AHB_CLK);
#endif

	INIT_GATE_CLK(AHB_AX_GATE, VA_PRCM_AHB_GAT1, 13, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_USB_GATE, VA_PRCM_AHB_GAT1, 16, CLK_ID_AHB_CLK);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(AHB_GMAC_GATE, VA_PRCM_AHB_GAT1, 18, CLK_ID_AHB_CLK);
#endif

	/* AHB BUS Reset Register 0 */
	INIT_GATE_CLK(AHB_DMA_RESET, VA_PRCM_AHB_RST0, 0, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_PTIMER_RESET, VA_PRCM_AHB_RST0, 1, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_AES_RESET, VA_PRCM_AHB_RST0, 6, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SDRAM_RESET, VA_PRCM_AHB_RST0, 16, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SDC0_RESET, VA_PRCM_AHB_RST0, 17, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SDC1_RESET, VA_PRCM_AHB_RST0, 18, CLK_ID_AHB_CLK);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(AHB_SDC2_RESET, VA_PRCM_AHB_RST0, 19, CLK_ID_AHB_CLK);
#endif

	INIT_GATE_CLK(AHB_SPI0_RESET, VA_PRCM_AHB_RST0, 21, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SPI1_RESET, VA_PRCM_AHB_RST0, 22, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_SPI2_RESET, VA_PRCM_AHB_RST0, 23, CLK_ID_AHB_CLK);

	/* AHB BUS Reset Register 1 */
	INIT_GATE_CLK(AHB_VISS_RESET, VA_PRCM_AHB_RST1, 0, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_DPU_RESET, VA_PRCM_AHB_RST1, 2, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_DOSS_RESET, VA_PRCM_AHB_RST1, 4, CLK_ID_AHB_CLK);

	/* VC */
#ifdef ARCH_LOMBO_N7V0
	INIT_GATE_CLK(AHB_VC_RESET, VA_PRCM_AHB_RST1, 12, CLK_ID_AHB_CLK);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(AHB_VC_DEC_RESET, VA_PRCM_AHB_RST1, 11, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_VC_ENC_RESET, VA_PRCM_AHB_RST1, 12, CLK_ID_AHB_CLK);
#endif

	INIT_GATE_CLK(AHB_AX_RESET, VA_PRCM_AHB_RST1, 13, CLK_ID_AHB_CLK);
	INIT_GATE_CLK(AHB_USB_RESET, VA_PRCM_AHB_RST1, 16, CLK_ID_AHB_CLK);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(AHB_GMAC_RESET, VA_PRCM_AHB_RST1, 18, CLK_ID_AHB_CLK);
#endif

	/* APB BUS Clock Gating Register 0 */
	INIT_GATE_CLK(APB_I2C0_GATE, VA_PRCM_APB_GAT0, 0, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2C1_GATE, VA_PRCM_APB_GAT0, 1, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2C2_GATE, VA_PRCM_APB_GAT0, 2, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2C3_GATE, VA_PRCM_APB_GAT0, 3, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART0_GATE, VA_PRCM_APB_GAT0, 8, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART1_GATE, VA_PRCM_APB_GAT0, 9, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART2_GATE, VA_PRCM_APB_GAT0, 10, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART3_GATE, VA_PRCM_APB_GAT0, 11, CLK_ID_APB_CLK);

	/* APB BUS Reset Reister 0 */
	INIT_GATE_CLK(APB_I2C0_RESET, VA_PRCM_APB_RST0, 0, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2C1_RESET, VA_PRCM_APB_RST0, 1, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2C2_RESET, VA_PRCM_APB_RST0, 2, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2C3_RESET, VA_PRCM_APB_RST0, 3, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART0_RESET, VA_PRCM_APB_RST0, 8, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART1_RESET, VA_PRCM_APB_RST0, 9, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART2_RESET, VA_PRCM_APB_RST0, 10, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_UART3_RESET, VA_PRCM_APB_RST0, 11, CLK_ID_APB_CLK);

	/* APB BUS Clock Gating Register 1 */
	/* I2S */
#ifdef ARCH_LOMBO_N7V0
	INIT_GATE_CLK(APB_I2S_GATE, VA_PRCM_APB_GAT1, 2, CLK_ID_APB_CLK);
#endif
#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(APB_I2S0_GATE, VA_PRCM_APB_GAT1, 2, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2S1_GATE, VA_PRCM_APB_GAT1, 3, CLK_ID_APB_CLK);
#endif

	INIT_GATE_CLK(APB_GPADC_GATE, VA_PRCM_APB_GAT1, 6, CLK_ID_APB_CLK);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(APB_IR_GATE, VA_PRCM_APB_GAT1, 8, CLK_ID_APB_CLK);
#endif

	INIT_GATE_CLK(APB_GPIO_GATE, VA_PRCM_APB_GAT1, 9, CLK_ID_APB_CLK);

	/* APB BUS Reset Register 1 */
#ifdef ARCH_LOMBO_N7V0
	INIT_GATE_CLK(APB_I2S_RESET, VA_PRCM_APB_RST1, 2, CLK_ID_APB_CLK);
#endif

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(APB_I2S0_RESET, VA_PRCM_APB_RST1, 2, CLK_ID_APB_CLK);
	INIT_GATE_CLK(APB_I2S1_RESET, VA_PRCM_APB_RST1, 3, CLK_ID_APB_CLK);
#endif

	INIT_GATE_CLK(APB_GPADC_RESET, VA_PRCM_APB_RST1, 6, CLK_ID_APB_CLK);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(APB_IR_RESET, VA_PRCM_APB_RST1, 8, CLK_ID_APB_CLK);
#endif

	INIT_GATE_CLK(APB_GPIO_RESET, VA_PRCM_APB_RST1, 9, CLK_ID_APB_CLK);

	/* AXI BUS Clock Gating Register */
	INIT_GATE_CLK(MAXI_DMA_GATE, VA_PRCM_AXI_GAT, 0, CLK_ID_MEM_AXI_CLK);

#ifdef ARCH_LOMBO_N7V0
	INIT_GATE_CLK(MAXI_VC_GATE, VA_PRCM_AXI_GAT, 1, CLK_ID_MEM_AXI_CLK);
#endif

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(MAXI_VC_ENC_GATE, VA_PRCM_AXI_GAT, 1, CLK_ID_MEM_AXI_CLK);
	INIT_GATE_CLK(MAXI_VC_DEC_GATE, VA_PRCM_AXI_GAT, 2, CLK_ID_MEM_AXI_CLK);
#endif

	INIT_GATE_CLK(MAXI_VISS0_GATE, VA_PRCM_AXI_GAT, 4, CLK_ID_MEM_AXI_CLK);
	INIT_GATE_CLK(MAXI_VISS1_GATE, VA_PRCM_AXI_GAT, 5, CLK_ID_MEM_AXI_CLK);
	INIT_GATE_CLK(MAXI_DPU_GATE, VA_PRCM_AXI_GAT, 8, CLK_ID_MEM_AXI_CLK);
	INIT_GATE_CLK(MAXI_DOSS_GATE, VA_PRCM_AXI_GAT, 10, CLK_ID_MEM_AXI_CLK);
	INIT_GATE_CLK(MAXI_AX_GATE, VA_PRCM_AXI_GAT, 12, CLK_ID_MEM_AXI_CLK);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(MAXI_GMAC_GATE, VA_PRCM_AXI_GAT, 18, CLK_ID_MEM_AXI_CLK);
#endif

	INIT_GATE_CLK(VISS_SCLK0, VA_PRCM_VISS_CLK_CTRL, 0, CLK_ID_PERH0_PLL_DIV2);
	INIT_GATE_CLK(VISS_SCLK1, VA_PRCM_VISS_CLK_CTRL, 8, CLK_ID_VC_PLL);
	INIT_GATE_CLK(VISS_SCLK2, VA_PRCM_VISS_CLK_CTRL, 16, CLK_ID_OSC24M);
	INIT_GATE_CLK(DPU_SCLK2, VA_PRCM_DPU_SCLK2_CLK_CTRL, 31, CLK_ID_OSC24M);

#ifdef ARCH_LOMBO_N7V0
	INIT_GATE_CLK(DOSS_SCLK0, VA_PRCM_DOSS_CLK_CTRL, 8, CLK_ID_VIDEO_PLL);
#endif

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(DOSS_SCLK0, VA_PRCM_DOSS_CLK_CTRL, 8, CLK_ID_DISP_PLL);
#endif

	INIT_GATE_CLK(DOSS_OSC24M, VA_PRCM_DOSS_CLK_CTRL, 0, CLK_ID_OSC24M);
	INIT_GATE_CLK(AES_CLK, VA_PRCM_AES_CLK_CTRL, 31, CLK_ID_OSC24M);
	INIT_GATE_CLK(USB_PHY_RESET, VA_PRCM_USB_PHY_RST, 0, 0);

#ifdef ARCH_LOMBO_N7V1
	INIT_GATE_CLK(IR_CLK, VA_PRCM_IR_CLK_CTRL, 31, CLK_ID_OSC24M);
#endif
}
