Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'drivers')
src     = Glob('*.c')
CPPPATH = [cwd, GetCurrentDir()]

group = DefineGroup('viss_common', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
