Import('RTT_ROOT')
#Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd,cwd+'/../../../../include',str(Dir('#'))]

group = DefineGroup('car_recorder_mod', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
