# RT-Thread building script for bridge

import os
from building import *

src = Glob('*.c')

cwd = GetCurrentDir()
CPPPATH = [cwd]

objs = []
list = os.listdir(cwd)

group = DefineGroup('disp', src, depend = ['ARCH_LOMBO_N7', 'LOMBO_DISP'], CPPPATH = CPPPATH)


for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs = objs + group

Return('objs')
