Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

#
# add local source and libs
#
src = Glob('*.c')
LIBS = Glob('*.a')
group = DefineGroup('Lib_release', src, depend = [''], CPPPATH = CPPPATH, LIBS = LIBS, LIBPATH = [cwd])

#
# add subdir's source and libs
#
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = group + objs

Return('group')

